query getNovostis($status: PublicationStatus) {
  novostis(sort: "publishedAt:desc", status: $status) {
    documentId
    title
    slug
    mainImage {
      url
      alternativeText
    }
    createdAt
    updatedAt
    publishedAt
  }
}
