query RezultatyRabotiesVideos($page: Int, $pageSize: Int) {
  rezultatyRaboties_connection(sort: "order:asc", pagination: { page: $page, pageSize: $pageSize }, filters: { isVideo: { eq: true } }) {
    nodes {
      documentId
      order
      contentVideo: content {
        __typename
        ... on ComponentResultsOfWorkSsylkaNaVideo {
          preview {
            url
            alternativeText
          }
          link
        }
      }
    }
    pageInfo {
      pageCount
      total
      pageSize
      page
    }
  }
}
